package com.rephoto.rephoto_api.client;

import com.rephoto.rephoto_api.dto.AiDescriptionResponseDto;
import lombok.RequiredArgsConstructor;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Component;
import org.springframework.web.client.RestTemplate;

import java.util.List;
import java.util.Map;

@Component
@RequiredArgsConstructor
public class AiClient {

    private final RestTemplate restTemplate = new RestTemplate();

    @Value("${ai.base-url:http://localhost:9000}")
    private String baseUrl;

    public AiDescriptionResponseDto generateDescription(Long photoId, String imageUrl) {
        // 미배포 시 스텁
        if (baseUrl == null || baseUrl.isBlank()) {
            return AiDescriptionResponseDto.builder()
                    .descriptionId(0L)
                    .description("example_description generated by ai")
                    .photoId(photoId)
                    .tagNames(List.of("바다", "여름", "여행"))
                    .vector(List.of(0.12, -0.34, 0.56))
                    .build();
        }

        Map<String, Object> request = Map.of("photoId", photoId, "imageUrl", imageUrl);
        return restTemplate.postForObject(baseUrl + "/ai/descriptions", request, AiDescriptionResponseDto.class);
    }
}
