package com.rephoto.rephoto_api.client;

import com.rephoto.rephoto_api.dto.ImageCaptionResponse;
import com.rephoto.rephoto_api.exception.CustomException;
import com.rephoto.rephoto_api.exception.ErrorCode;
import lombok.RequiredArgsConstructor;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.core.io.ByteArrayResource;
import org.springframework.core.io.Resource;
import org.springframework.http.*;
import org.springframework.stereotype.Component;
import org.springframework.util.LinkedMultiValueMap;
import org.springframework.util.MultiValueMap;
import org.springframework.web.client.HttpClientErrorException;
import org.springframework.web.client.RestTemplate;

import java.io.InputStream;
import java.net.URL;
import java.net.URLConnection;
import java.util.List;

@Component
@RequiredArgsConstructor
public class AiClient {

    private final RestTemplate restTemplate = new RestTemplate();

    @Value("${ai.base-url:http://localhost:9000}")
    private String baseUrl;

    public ImageCaptionResponse generateCaptionByUrl(Long photoId, String imageUrl) {
        // 1) 미배포/로컬 스텁
        if (baseUrl == null || baseUrl.isBlank()) {
            ImageCaptionResponse stub = new ImageCaptionResponse();
            stub.setExplanation("example_description generated by ai");
            stub.setTags(List.of("바다", "여름", "여행"));
            stub.setExplanation_embedding(List.of(0.12, -0.34, 0.56));
            return stub;
        }

        try {
            // 1) URL → bytes
            URL url = new URL(imageUrl);
            URLConnection conn = url.openConnection();
            byte[] bytes;
            try (InputStream in = conn.getInputStream()) {
                bytes = in.readAllBytes();
            }

            String filename = extractFilename(imageUrl, "image.jpg");
            String contentType = conn.getContentType();
            if (contentType == null || contentType.isBlank()) {
                contentType = guessContentType(filename, "image/jpeg");
            }

            // 2) 파일 파트 준비
            ByteArrayResource resource = new ByteArrayResource(bytes) {
                @Override public String getFilename() { return filename; }
            };

            HttpHeaders partHeaders = new HttpHeaders();
            partHeaders.setContentType(MediaType.parseMediaType(contentType));
            // Content-Disposition은 RestTemplate가 filename 참고해서 넣어줌 (필요시 수동 세팅 가능)

            HttpEntity<Resource> filePart = new HttpEntity<>(resource, partHeaders);

            // 3) 멀티파트 바디
            MultiValueMap<String, Object> body = new LinkedMultiValueMap<>();
            body.add("file", filePart); // 🔴 Swagger에서 필드명이 'file' 임을 확인했음

            // 4) 요청 헤더 (멀티파트)
            HttpHeaders headers = new HttpHeaders();
            headers.setContentType(MediaType.MULTIPART_FORM_DATA);

            HttpEntity<MultiValueMap<String, Object>> request = new HttpEntity<>(body, headers);

            // 5) 호출
            String api = baseUrl + "/api/ai/caption/generate";
            ResponseEntity<ImageCaptionResponse> res = restTemplate.exchange(
                    api, HttpMethod.POST, request, ImageCaptionResponse.class
            );
            return res.getBody();

        } catch (HttpClientErrorException.UnprocessableEntity e) {
            // 422 → 커스텀 코드로 매핑
            throw new CustomException(ErrorCode.AI_VALIDATION_ERROR);
        } catch (Exception e) {
            throw new RuntimeException("AI caption(URL) 생성 중 오류 발생", e);
        }
    }

    private String extractFilename(String url, String fallback) {
        try {
            String path = new URL(url).getPath();
            String name = path.substring(path.lastIndexOf('/') + 1);
            return (name == null || name.isBlank()) ? fallback : name;
        } catch (Exception e) { return fallback; }
    }

    private String guessContentType(String filename, String fallback) {
        String f = filename.toLowerCase();
        if (f.endsWith(".png")) return "image/png";
        if (f.endsWith(".webp")) return "image/webp";
        if (f.endsWith(".jpg") || f.endsWith(".jpeg")) return "image/jpeg";
        return fallback;
    }
}
